# Generated by Django 4.2.6 on 2023-10-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalMarketing',
        ),
        migrations.DeleteModel(
            name='OurTeam',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
        migrations.DeleteModel(
            name='video',
        ),
    ]
