# Generated by Django 4.2.6 on 2023-10-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_digitalmarketing_delete_ourteam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategorie',
            name='icons',
        ),
    ]
