# Generated by Django 4.2.6 on 2023-10-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_maincategorie_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='feature',
        ),
    ]
