# Generated by Django 4.2.6 on 2023-10-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_news_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.CharField(blank=True, default='(२०८०-आश्विन-शुक्रबार)', editable=False, max_length=50, null=True),
        ),
    ]
