# Generated by Django 4.2.6 on 2023-10-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_news_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.CharField(blank=True, default='(२०८०-कार्तिक-बुधवार)', editable=False, max_length=50, null=True),
        ),
    ]
