# Generated by Django 4.2.6 on 2023-10-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
